"""Add workout_log table

Revision ID: 12654ede5f2f
Revises: 83247814b974
Create Date: 2025-11-25 11:15:05.957112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12654ede5f2f'
down_revision: Union[str, None] = '83247814b974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('day_type', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_log_date'), 'workout_log', ['date'], unique=False)
    op.create_index(op.f('ix_workout_log_id'), 'workout_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_log_id'), table_name='workout_log')
    op.drop_index(op.f('ix_workout_log_date'), table_name='workout_log')
    op.drop_table('workout_log')
    # ### end Alembic commands ###
