"""add food log table

Revision ID: 26e73327296c
Revises: a656dd56cf5e
Create Date: 2025-11-21 11:58:05.773355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e73327296c'
down_revision: Union[str, None] = 'a656dd56cf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_food_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_item.food_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_user_food_log_log_id'), 'user_food_log', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_food_log_log_id'), table_name='user_food_log')
    op.drop_table('user_food_log')
    # ### end Alembic commands ###
