"""add_food_tables_final

Revision ID: 3a0c1a737a48
Revises: 2d7415626542
Create Date: 2025-11-11 11:04:29.626318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0c1a737a48'
down_revision: Union[str, None] = '2d7415626542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_type',
    sa.Column('diet_type_id', sa.Integer(), nullable=False),
    sa.Column('diet_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('diet_type_id'),
    sa.UniqueConstraint('diet_name')
    )
    op.create_index(op.f('ix_diet_type_diet_type_id'), 'diet_type', ['diet_type_id'], unique=False)
    op.create_table('food_item',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('kcal_100g', sa.Float(), nullable=True),
    sa.Column('protein_100g', sa.Float(), nullable=True),
    sa.Column('carbs_100g', sa.Float(), nullable=True),
    sa.Column('fat_100g', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_index(op.f('ix_food_item_food_id'), 'food_item', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_item_food_name'), 'food_item', ['food_name'], unique=False)
    op.create_table('food_allergen_link',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.allergen_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food_item.food_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'allergen_id')
    )
    op.create_table('food_diet_type_link',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('diet_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_type_id'], ['diet_type.diet_type_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food_item.food_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'diet_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_diet_type_link')
    op.drop_table('food_allergen_link')
    op.drop_index(op.f('ix_food_item_food_name'), table_name='food_item')
    op.drop_index(op.f('ix_food_item_food_id'), table_name='food_item')
    op.drop_table('food_item')
    op.drop_index(op.f('ix_diet_type_diet_type_id'), table_name='diet_type')
    op.drop_table('diet_type')
    # ### end Alembic commands ###
