"""food_item db upgrade

Revision ID: 6252e2bf7c2b
Revises: 12654ede5f2f
Create Date: 2025-11-25 15:09:22.896414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6252e2bf7c2b'
down_revision: Union[str, None] = '12654ede5f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_item', sa.Column('food_category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_food_item_food_category'), 'food_item', ['food_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_item_food_category'), table_name='food_item')
    op.drop_column('food_item', 'food_category')
    # ### end Alembic commands ###
