"""streak added

Revision ID: 712fc949fe36
Revises: a45e60556fe8
Create Date: 2025-12-02 01:53:21.737491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712fc949fe36'
down_revision: Union[str, None] = 'a45e60556fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('login_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_streak')
    op.drop_column('user', 'last_login_date')
    # ### end Alembic commands ###
