"""add physical_activities

Revision ID: 7d9c712aa7e3
Revises: 3a0c1a737a48
Create Date: 2025-11-17 13:51:45.528307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9c712aa7e3'
down_revision: Union[str, None] = '3a0c1a737a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compendium_code', sa.String(), nullable=True),
    sa.Column('major_heading', sa.String(), nullable=True),
    sa.Column('specific_activities', sa.String(), nullable=False),
    sa.Column('met', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_activities_compendium_code'), 'physical_activities', ['compendium_code'], unique=False)
    op.create_index(op.f('ix_physical_activities_id'), 'physical_activities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_physical_activities_id'), table_name='physical_activities')
    op.drop_index(op.f('ix_physical_activities_compendium_code'), table_name='physical_activities')
    op.drop_table('physical_activities')
    # ### end Alembic commands ###
