"""add macros to diet_profile v2

Revision ID: 83247814b974
Revises: 0217d4443022
Create Date: 2025-11-24 23:19:03.967517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83247814b974'
down_revision: Union[str, None] = '0217d4443022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet_profile', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('diet_profile', sa.Column('protein', sa.Float(), nullable=True))
    op.add_column('diet_profile', sa.Column('carbs', sa.Float(), nullable=True))
    op.add_column('diet_profile', sa.Column('fat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diet_profile', 'fat')
    op.drop_column('diet_profile', 'carbs')
    op.drop_column('diet_profile', 'protein')
    op.drop_column('diet_profile', 'calories')
    # ### end Alembic commands ###
