"""add exercises table

Revision ID: a656dd56cf5e
Revises: 7d9c712aa7e3
Create Date: 2025-11-17 14:18:11.658235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a656dd56cf5e'
down_revision: Union[str, None] = '7d9c712aa7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_hu', sa.String(), nullable=True),
    sa.Column('force', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('primary_muscles', sa.String(), nullable=True),
    sa.Column('secondary_muscles', sa.String(), nullable=True),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_physical_activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_physical_activity_id'], ['physical_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_external_id'), 'exercises', ['external_id'], unique=True)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_external_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
