"""demo mode add

Revision ID: ad161a849d87
Revises: f94efeb8284a
Create Date: 2025-12-05 06:13:51.186867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad161a849d87'
down_revision: Union[str, None] = 'f94efeb8284a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_item', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=True))
    op.create_index(op.f('ix_food_item_is_demo'), 'food_item', ['is_demo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_item_is_demo'), table_name='food_item')
    op.drop_column('food_item', 'is_demo')
    # ### end Alembic commands ###
